- name: Deploy app
  hosts: app
  become: true
  tasks:
    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      notify: restart puma
      
  handlers:
    - name: restart puma
      systemd: name=puma state=restarted
